/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Layout: typeof import('./src/components/Layout.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Admin/Search.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    Table: typeof import('./src/components/Admin/Table.vue')['default']
    TableLayout: typeof import('./src/components/TableLayout.vue')['default']
    TeamList: typeof import('./src/components/TeamList.vue')['default']
  }
}
